Gemfile.lock, app/views/rentals/rental_request_list.html.erb
added the view, not sure if the names are correct pls check, did not delete the other view file Reyna made (new.html) bc this is a different view file (requests list). added some random gem thing idk what it is.
=> added rental request list view

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/costumes_controller.rb, app/controllers/pages_controller.rb, app/models/costume.rb, app/views/costumes/index.html.erb, app/views/costumes/show.html.erb, app/views/pages/home.html.erb, config/environments/development.rb, config/environments/production.rb, config/routes.rb, config/storage.yml, db/migrate/20250722130219_add_category_to_costumes.rb, db/schema.rb, db/seeds.rb, test/controllers/costumes_controller_test.rb
=> Costume homepage

Gemfile, app/views/pages/home.html.erb, db/schema.rb, db/seeds.rb
resolved santa issue that was preventing anime and other categories from being loaded
=> edited homepage, resolved santa issue

app/views/costumes/show.html.erb, app/views/rentals/new.html.erb
added a button at the bottom of the costumes details page to start a costumes rental request form. added costume photo to rental request page
=> Linked costumes details page to costumes rental request form

app/assets/stylesheets/pages/_home.scss, app/controllers/costumes_controller.rb, app/controllers/pages_controller.rb, app/javascript/controllers/search_controller.js, app/views/costumes/_card.html.erb, app/views/costumes/index.html.erb, app/views/pages/home.html.erb, config/routes.rb
=> Homepage costume details page update

app/views/rentals/new.html.erb
added total price code to the new.html.erb
=> Total price function

app/views/costumes/show.html.erb
Photo added to costume details page
=> Photo added to costumes details page

app/views/costumes/show.html.erb, app/views/rentals/new.html.erb, config/initializers/cloudinary.rb
=> Decimal places

app/views/rentals/index.html.erb
added some style to the my rental request list page
=> updated style of rental list

app/views/costumes/show.html.erb
centered everything, made button bigger, and added vertical margins
=> css for costumes details page

app/views/rentals/index.html.erb
changed to yen and reverse chronological order for costumes on rental list page
=> updated rental list page

app/javascript/controllers/image_switcher_controller.js, app/views/costumes/show.html.erb
=> Updated show page

app/controllers/rentals_controller.rb, app/models/rental.rb, app/views/rentals/index.html.erb, app/views/rentals/new.html.erb, app/views/rentals/owner_requests.html.erb, db/migrate/20250731111214_change_status_to_integer_in_rentals.rb, db/schema.rb
changed status from string to enum
=> Updated status on owner and user's rental request index pages

app/controllers/costumes_controller.rb, app/views/costumes/_form.html.erb, app/views/costumes/show.html.erb
i pushed to the wrong branch but this is for create costume - show costume connection
=> fixed create costume - show costume connection

app/views/costumes/show.html.erb
small update: added category moniker
=> updates show page, to show which category costume belongs to

db/seeds.rb
still need help manually adding photos to seed!
=> added functionality for more photos, need more photos

app/controllers/costumes_controller.rb, app/views/costumes/show.html.erb
categories work on show page now!
=> updated show page to implment categories

app/views/costumes/_card.html.erb, app/views/costumes/my_listings.html.erb, app/views/rentals/index.html.erb
added my listings page and updated rental requests page
=> added my listings page

app/controllers/rentals_controller.rb, app/views/costumes/_form.html.erb, app/views/costumes/new.html.erb, app/views/rentals/index.html.erb, app/views/rentals/new.html.erb, db/schema.rb
improved new costume form and changed yen to euro
=> Fixed new costume form

app/views/costumes/_card.html.erb, app/views/costumes/my_listings.html.erb, app/views/rentals/new.html.erb
added edit and delete buttons (not working yet), fixed total price +1 day issue, fixed pictures
=> made some visual changes

db/seeds.rb
=> more photos

app/javascript/application.js, app/views/costumes/index.html.erb, app/views/pages/home.html.erb, app/views/rentals/new.html.erb, app/views/rentals/owner_requests.html.erb, app/views/shared/_search_form.html.erb
Search bar added to the search results pages and date picker changed to be that you cannot pick a date earlier than current
=> Search bar added

app/controllers/costumes_controller.rb, config/routes.rb
=> improve search

app/controllers/costumes_controller.rb, app/views/costumes/_card.html.erb
added delete button to my costumes page
=> added delete button to my costumes
